### ISSUE TITLE
Minor Editing required in transformer.py

### ISSUE THREAD

**Issue by mustansarfiaz** [Kitware/COAT#1]
Dear Author,

I found your work very interesting. I find minor typo mistakes in your code in transformer.py. Please cross-check from lines 173 to 193.
Here are changes that may be required:
1)-change feature_aug_type  to self.feature_aug_type 
2)-indent error from line 187 to 193.

**Comment by mustansarfiaz** [comment]
Dear author,
Also, update your citation block in readme.md.

**Comment by daweidu** [comment]
The typo mistakes fixed. Thanks!
