### ISSUE TITLE
 CUHK-SYSU dataset results are not reproduced successfully.

### ISSUE THREAD

**Issue by mustansarfiaz** [Kitware/COAT#2]
Dear authors,
I found your paper very interesting. 
I was trying to reproduce your results over CUHK-SYSU dataset but failed. However, I can successfully reproduce results over PRW dataset. I request you to please help me in this regard.
On CYHK-SYSU dataset, I got mAP = 93.34%
top- 1 = 94.00%.

Thank you.

**Comment by daweidu** [comment]
The model for CUHK-SYSU is trained with slightly different hyper-parameters from PRW. For your convinience, the config file for CUHK-SYSU is updated. The results should be reproduced by using the new config file. Thanks.
